image: "rust:latest"

stages:
    - test
    - build

test:
    stage: test
    script:
        - rustc --version && cargo --version      # Print version info for debugging
        - cargo test --all --verbose
build:
    stage: build
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/vidocq
