image: "rust:latest"

before_script:
    - curl https://sh.rustup.rs -ysSf | sh

# Use cargo to test the project
test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
