language: rust
dist: trusty
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings -A clippy::trivial-regex
  - cargo build --verbose --all --release
  - cargo test --verbose --all
deploy:
    provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "target/release/vidocq"
    skip_cleanup: true
    draft: true
