language: rust
dist: trusty
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - make check
  - make test
  - make build
deploy:
    provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "target/release/vidocq"
    skip_cleanup: true
    draft: true
    on:
        branch: master
        tags: true
