language: rust
rust:
  - stable
  - beta
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings -A clippy::trivial-regex
  - cargo build --verbose --all
  - cargo test --verbose --all

