[package]
name = "vidocq"
version = "0.1.1"
authors = ["macarrie <mathieu0carrie@gmail.com>"]

[dependencies]
regex = "1.0.0"
lazy_static = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
matches = "0.1.6"
clap = "2.31"
